management.endpoints.web.exposure.include: '*'
management.endpoint:
  metrics.enabled: true
  prometheus.enabled: true
  health.show-details: always
management.metrics.export.prometheus.enabled: true

client:
  pokeapi.basePath: https://pokeapi.co/api/v2
  funtranslator.basePath: https://api.funtranslations.com
