version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1

references:
  default-executor: &default-executor
    docker:
      - image: circleci/openjdk:11

  default-working-directory: &default-working-directory
    working_directory: ~/circleci-shakespearean-pokemon

  restore-maven-cache: &restore-maven-cache
    restore_cache:
      key: m2-{{ checksum "pom.xml" }}

  save-maven-cache: &save-maven-cache
    save_cache:
      paths:
        - ~/.m2
      key: m2-{{ checksum "pom.xml" }}

jobs:
  build:
    <<: *default-executor
    <<: *default-working-directory
    steps:
      - checkout
      - *restore-maven-cache
      - run: mvn package -Dskip.unit.test=true -Dskip.integration.test=true
      - *save-maven-cache
  unit_tests:
    <<: *default-executor
    <<: *default-working-directory
    steps:
      - checkout
      - *restore-maven-cache
      - run: ./mvnw test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/jacoco-reports
      - codecov/upload
          file: target/jacoco-reports/jacoco.xml
  integration_tests:
    <<: *default-executor
    <<: *default-working-directory
    steps:
      - checkout
      - *restore-maven-cache
      - run: ./mvnw integration-test -Dskip.unit.test=true
      - store_test_results:
          path: target/failsafe-reports

workflows:
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - integration_tests:
          requires:
            - build